// Barrel export for all firestore modules
// This allows existing imports to continue working unchanged

export * from './users'
export * from './daily-logs'
export * from './signals'
export * from './projects'
export * from './weekly-synthesis'
export * from './focus-sessions'
export * from './garmin'
export * from './conversations'
export * from './contacts'
export * from './external-signals'
export * from './daily-reports'
export * from './audio-transforms'
export * from './exploration-routes'
export * from './goals'
export * from './financial'
export * from './insights'
export * from './macro-patterns'
export * from './network-contacts'
export * from './sales-assessments'
